---

onp_adams:
  hosts:
    onp-adams-fe-01:
      ansible_host: 192.168.100.121
    onp-adams-be-01:
      ansible_host:

onp_ade:
  hosts:
    onp-ade-fe-01:
      ansible_host: 192.168.100.122
    onp-ade-be-01:
      ansible_host:

onp_vitae:
  hosts:
    onp-vitae-fe-01:
      ansible_host: 192.168.100.123
    onp-vitae-be-01:
      ansible_host:

aws_adams:
  hosts:
    aws-adams-fe-02:
      ansible_host:
    aws-adams-be-02:
      ansible_host:

aws_ade:
  hosts:
    aws-ade-fe-02:
      ansible_host:
    aws-ade-be-02:
      ansible_host:

aws_vitae:
  hosts:
    aws-vitae-fe-02:
      ansible_host:
    aws-vitae-be-02:
      ansible_host:

onprem_frontend:
  hosts:
    onp-adams-fe-01:
    onp-ade-fe-01:
    onp-vitae-fe-01:

onprem_backend:
  hosts:
    onp-adams-be-01:
    onp-ade-be-01:
    onp-vitae-be-01:

aws_frontend:
  hosts:
    aws-adams-fe-02:
    aws-ade-fe-02:
    aws-vitae-fe-02:

aws_backend:
  hosts:
    aws-adams-be-02:
    aws-ade-be-02:
    aws-vitae-be-02:

frontend:
  children:
    onprem_frontend:
    aws_frontend:

backend: 
  children:
    onprem_backend:
    aws_backend:

onprem:
  children:
    onprem_frontend:
    onprem_backend:

aws:
  children:
    aws_frontend:
    aws_backend:

adams:
  children:
    onp_adams:
    aws_adams:

ade:
  children:
    onp_ade:
    aws_ade:

vitae:
  children:
    onp_vitae:
    aws_vitae: